/* GENERATED by scripts/tokens/build.mjs from tokens/**. Do not edit by hand. */

/** Brand palette: exact hex from the brand DTCG file, with its OKLCH equivalent. */
export const palette = {
  "ink-50": {
    "hex": "#F1F6FF",
    "oklch": "oklch(97.20% 0.0132 262.38)"
  },
  "ink-100": {
    "hex": "#E3ECFB",
    "oklch": "oklch(94.07% 0.0225 260.72)"
  },
  "ink-200": {
    "hex": "#CAD9F3",
    "oklch": "oklch(88.21% 0.0394 261.51)"
  },
  "ink-300": {
    "hex": "#ADC1E5",
    "oklch": "oklch(80.78% 0.0556 262.18)"
  },
  "ink-400": {
    "hex": "#8EA6D1",
    "oklch": "oklch(72.24% 0.0685 261.96)"
  },
  "ink-500": {
    "hex": "#7089B6",
    "oklch": "oklch(62.82% 0.0742 261.91)"
  },
  "ink-600": {
    "hex": "#556C96",
    "oklch": "oklch(53.05% 0.0720 262.07)"
  },
  "ink-700": {
    "hex": "#3F5377",
    "oklch": "oklch(44.18% 0.0647 261.74)"
  },
  "ink-800": {
    "hex": "#2B3B57",
    "oklch": "oklch(35.18% 0.0535 261.20)"
  },
  "ink-900": {
    "hex": "#141E2D",
    "oklch": "oklch(23.32% 0.0326 258.29)"
  },
  "ink-950": {
    "hex": "#0E1722",
    "oklch": "oklch(20.16% 0.0259 253.90)"
  },
  "bronze-50": {
    "hex": "#FBF5EC",
    "oklch": "oklch(97.23% 0.0136 78.26)"
  },
  "bronze-100": {
    "hex": "#F3EADC",
    "oklch": "oklch(94.03% 0.0210 79.09)"
  },
  "bronze-200": {
    "hex": "#E6D6BD",
    "oklch": "oklch(88.25% 0.0378 79.09)"
  },
  "bronze-300": {
    "hex": "#D4BD9A",
    "oklch": "oklch(80.90% 0.0539 78.22)"
  },
  "bronze-400": {
    "hex": "#C5A572",
    "oklch": "oklch(73.86% 0.0773 78.76)"
  },
  "bronze-500": {
    "hex": "#A8895C",
    "oklch": "oklch(64.84% 0.0719 76.23)"
  },
  "bronze-600": {
    "hex": "#8A6E45",
    "oklch": "oklch(55.59% 0.0673 76.18)"
  },
  "bronze-700": {
    "hex": "#664F29",
    "oklch": "oklch(44.27% 0.0623 78.59)"
  },
  "bronze-800": {
    "hex": "#4A3819",
    "oklch": "oklch(35.32% 0.0526 79.28)"
  },
  "bronze-900": {
    "hex": "#32240D",
    "oklch": "oklch(27.13% 0.0418 77.83)"
  },
  "bronze-950": {
    "hex": "#1F1505",
    "oklch": "oklch(20.41% 0.0326 78.43)"
  },
  "verdant-50": {
    "hex": "#EEF9F2",
    "oklch": "oklch(97.20% 0.0148 158.25)"
  },
  "verdant-100": {
    "hex": "#DEF1E5",
    "oklch": "oklch(94.08% 0.0256 158.19)"
  },
  "verdant-200": {
    "hex": "#C1E2CD",
    "oklch": "oklch(88.30% 0.0450 157.44)"
  },
  "verdant-300": {
    "hex": "#9FCDB1",
    "oklch": "oklch(80.78% 0.0624 157.95)"
  },
  "verdant-400": {
    "hex": "#7BB593",
    "oklch": "oklch(72.35% 0.0784 158.00)"
  },
  "verdant-500": {
    "hex": "#599875",
    "oklch": "oklch(62.70% 0.0847 158.39)"
  },
  "verdant-600": {
    "hex": "#3F7B5A",
    "oklch": "oklch(53.26% 0.0822 157.87)"
  },
  "verdant-700": {
    "hex": "#2B5F43",
    "oklch": "oklch(44.12% 0.0732 157.85)"
  },
  "verdant-800": {
    "hex": "#1B452F",
    "oklch": "oklch(35.35% 0.0612 158.11)"
  },
  "verdant-900": {
    "hex": "#0E2E1D",
    "oklch": "oklch(27.16% 0.0495 157.35)"
  },
  "verdant-950": {
    "hex": "#051C10",
    "oklch": "oklch(20.35% 0.0385 158.23)"
  },
  "amber-50": {
    "hex": "#FFF4E4",
    "oklch": "oklch(97.15% 0.0242 77.46)"
  },
  "amber-100": {
    "hex": "#FDE8CD",
    "oklch": "oklch(94.09% 0.0423 74.16)"
  },
  "amber-200": {
    "hex": "#F5D2A3",
    "oklch": "oklch(88.22% 0.0727 74.79)"
  },
  "amber-300": {
    "hex": "#E8B672",
    "oklch": "oklch(80.70% 0.1034 73.98)"
  },
  "amber-400": {
    "hex": "#D5983B",
    "oklch": "oklch(72.27% 0.1291 74.16)"
  },
  "amber-500": {
    "hex": "#BA7900",
    "oklch": "oklch(62.90% 0.1347 72.01)"
  },
  "amber-600": {
    "hex": "#995D00",
    "oklch": "oklch(53.35% 0.1177 67.26)"
  },
  "amber-700": {
    "hex": "#794600",
    "oklch": "oklch(44.51% 0.1001 64.75)"
  },
  "amber-800": {
    "hex": "#593000",
    "oklch": "oklch(35.43% 0.0815 62.06)"
  },
  "amber-900": {
    "hex": "#3D1E00",
    "oklch": "oklch(27.24% 0.0638 60.08)"
  },
  "amber-950": {
    "hex": "#281100",
    "oklch": "oklch(20.80% 0.0495 58.50)"
  },
  "oxblood-50": {
    "hex": "#FFF1ED",
    "oklch": "oklch(96.80% 0.0161 36.53)"
  },
  "oxblood-100": {
    "hex": "#FFE3DD",
    "oklch": "oklch(93.71% 0.0320 32.06)"
  },
  "oxblood-200": {
    "hex": "#FDCBBF",
    "oklch": "oklch(88.26% 0.0595 33.78)"
  },
  "oxblood-300": {
    "hex": "#F2AD9D",
    "oklch": "oklch(80.88% 0.0848 33.50)"
  },
  "oxblood-400": {
    "hex": "#DF8C7A",
    "oklch": "oklch(72.16% 0.1055 32.95)"
  },
  "oxblood-500": {
    "hex": "#C46D5A",
    "oklch": "oklch(62.87% 0.1148 33.34)"
  },
  "oxblood-600": {
    "hex": "#A25241",
    "oklch": "oklch(53.24% 0.1098 33.24)"
  },
  "oxblood-700": {
    "hex": "#8A4B3C",
    "oklch": "oklch(48.51% 0.0891 34.38)"
  },
  "oxblood-800": {
    "hex": "#5F281D",
    "oklch": "oklch(35.23% 0.0832 32.88)"
  },
  "oxblood-900": {
    "hex": "#421810",
    "oklch": "oklch(27.19% 0.0674 32.53)"
  },
  "oxblood-950": {
    "hex": "#2B0C06",
    "oklch": "oklch(20.51% 0.0535 33.64)"
  },
  "azure-50": {
    "hex": "#EBF8FF",
    "oklch": "oklch(97.15% 0.0167 230.90)"
  },
  "azure-100": {
    "hex": "#D9EEFF",
    "oklch": "oklch(93.88% 0.0321 242.35)"
  },
  "azure-200": {
    "hex": "#B9DDFC",
    "oklch": "oklch(88.18% 0.0574 244.48)"
  },
  "azure-300": {
    "hex": "#93C7F2",
    "oklch": "oklch(80.88% 0.0818 243.98)"
  },
  "azure-400": {
    "hex": "#6BACE0",
    "oklch": "oklch(72.14% 0.1012 243.99)"
  },
  "azure-500": {
    "hex": "#478FC6",
    "oklch": "oklch(62.76% 0.1102 243.97)"
  },
  "azure-600": {
    "hex": "#2C72A5",
    "oklch": "oklch(53.22% 0.1060 243.96)"
  },
  "azure-700": {
    "hex": "#195883",
    "oklch": "oklch(44.30% 0.0940 243.43)"
  },
  "azure-800": {
    "hex": "#0B3E61",
    "oklch": "oklch(35.10% 0.0795 244.52)"
  },
  "azure-900": {
    "hex": "#032944",
    "oklch": "oklch(27.14% 0.0647 245.06)"
  },
  "azure-950": {
    "hex": "#00192C",
    "oklch": "oklch(20.52% 0.0500 243.39)"
  },
  "neutral-50": {
    "hex": "#F5F6F7",
    "oklch": "oklch(97.27% 0.0017 247.84)"
  },
  "neutral-100": {
    "hex": "#EAEBED",
    "oklch": "oklch(93.99% 0.0029 264.54)"
  },
  "neutral-200": {
    "hex": "#D6D8DC",
    "oklch": "oklch(88.18% 0.0059 264.53)"
  },
  "neutral-300": {
    "hex": "#BEC0C5",
    "oklch": "oklch(80.77% 0.0073 268.53)"
  },
  "neutral-400": {
    "hex": "#A2A5AB",
    "oklch": "oklch(72.13% 0.0093 264.51)"
  },
  "neutral-500": {
    "hex": "#85898F",
    "oklch": "oklch(62.87% 0.0101 258.35)"
  },
  "neutral-600": {
    "hex": "#696C72",
    "oklch": "oklch(53.07% 0.0101 264.48)"
  },
  "neutral-700": {
    "hex": "#505358",
    "oklch": "oklch(44.13% 0.0090 260.73)"
  },
  "neutral-800": {
    "hex": "#393B3F",
    "oklch": "oklch(35.19% 0.0074 264.47)"
  },
  "neutral-900": {
    "hex": "#25272A",
    "oklch": "oklch(27.19% 0.0063 258.36)"
  },
  "neutral-950": {
    "hex": "#161719",
    "oklch": "oklch(20.44% 0.0043 264.47)"
  },
  "cream": {
    "hex": "#F4F1EA",
    "oklch": "oklch(95.85% 0.0098 87.47)"
  },
  "cream-raised": {
    "hex": "#FAF8F3",
    "oklch": "oklch(97.93% 0.0070 88.64)"
  },
  "white": {
    "hex": "#FFFFFF",
    "oklch": "oklch(100.00% 0.0000 0.00)"
  },
  "black": {
    "hex": "#0A0E14",
    "oklch": "oklch(16.25% 0.0143 258.36)"
  }
} as const;

/** Semantic colour roles per scope (resolved values). */
export const roles = {
  "light": {
    "surface-canvas": "#F4F1EA",
    "surface-raised": "#FAF8F3",
    "surface-overlay": "#FFFFFF",
    "fg": "#2A2E35",
    "fg-muted": "#5C6470",
    "fg-eyebrow": "#664F29",
    "fg-gilt": "#8A6E45",
    "border-hairline": "rgba(138,110,69,0.28)",
    "border-strong": "#8A6E45",
    "accent": "#A8895C",
    "gilt": "#C5A572",
    "action-bg": "#141E2D",
    "action-bg-hover": "#2B3B57",
    "action-fg": "#F4F1EA",
    "focus-ring": "#8A6E45",
    "state-success": "#2B5F43",
    "state-warning": "#995D00",
    "state-error": "#8A4B3C",
    "state-info": "#195883",
    "scrim": "rgba(14, 23, 34, 0.78)",
    "selection-bg": "#C5A572",
    "selection-fg": "#0E1722"
  },
  "dark": {
    "surface-canvas": "#0E1722",
    "surface-raised": "#16202E",
    "surface-overlay": "#1E2A3A",
    "fg": "#ECEAE2",
    "fg-muted": "#9FA8B4",
    "fg-eyebrow": "#C5A572",
    "fg-gilt": "#C5A572",
    "border-hairline": "rgba(197,165,114,0.22)",
    "border-strong": "#A8895C",
    "accent": "#C5A572",
    "gilt": "#C5A572",
    "action-bg": "#C5A572",
    "action-bg-hover": "#D4BD9A",
    "action-fg": "#0E1722",
    "focus-ring": "#C5A572",
    "state-success": "#9FCDB1",
    "state-warning": "#E8B672",
    "state-error": "#F2AD9D",
    "state-info": "#93C7F2",
    "scrim": "rgba(14, 23, 34, 0.78)",
    "selection-bg": "#C5A572",
    "selection-fg": "#0E1722"
  },
  "inverse": {
    "surface-canvas": "#141E2D",
    "surface-raised": "#16202E",
    "surface-overlay": "#1E2A3A",
    "fg": "#F4F1EA",
    "fg-muted": "#9FA8B4",
    "fg-eyebrow": "#C5A572",
    "fg-gilt": "#C5A572",
    "border-hairline": "rgba(197,165,114,0.22)",
    "border-strong": "#A8895C",
    "accent": "#C5A572",
    "gilt": "#C5A572",
    "action-bg": "#C5A572",
    "action-bg-hover": "#D4BD9A",
    "action-fg": "#0E1722",
    "focus-ring": "#C5A572",
    "state-success": "#9FCDB1",
    "state-warning": "#E8B672",
    "state-error": "#F2AD9D",
    "state-info": "#93C7F2",
    "scrim": "rgba(14, 23, 34, 0.78)",
    "selection-bg": "#C5A572",
    "selection-fg": "#0E1722"
  },
  "inverse-dark": {
    "surface-canvas": "#0A0E14",
    "surface-raised": "#0E1722",
    "surface-overlay": "#16202E",
    "fg": "#ECEAE2",
    "fg-muted": "#9FA8B4",
    "fg-eyebrow": "#C5A572",
    "fg-gilt": "#C5A572",
    "border-hairline": "rgba(197,165,114,0.22)",
    "border-strong": "#A8895C",
    "accent": "#C5A572",
    "gilt": "#C5A572",
    "action-bg": "#C5A572",
    "action-bg-hover": "#D4BD9A",
    "action-fg": "#0E1722",
    "focus-ring": "#C5A572",
    "state-success": "#9FCDB1",
    "state-warning": "#E8B672",
    "state-error": "#F2AD9D",
    "state-info": "#93C7F2",
    "scrim": "rgba(10, 14, 20, 0.8)",
    "selection-bg": "#C5A572",
    "selection-fg": "#0E1722"
  }
} as const;

export type Scope = keyof typeof roles;
export type Role = keyof (typeof roles)["light"];

/** Cubic-bézier curves (Motion/GSAP-ready arrays). */
export const ease = {"linear":[0,0,1,1],"standard":[0.2,0.7,0.2,1],"accelerate":[0.4,0,1,1],"in-out":[0.65,0,0.35,1],"emphasized":[0.2,0,0,1],"settle":[0.34,1.16,0.64,1]} as const satisfies Record<string, readonly [number, number, number, number]>;

/** Durations in seconds. */
export const duration = {"instant":0,"fast":0.1,"normal":0.2,"slow":0.3,"deliberate":0.5} as const;

export const motion = {
  reveal: { duration: 0.5, ease: ease.emphasized, distance: 16 },
  stagger: { interval: 0.04, cap: 8 },
  hover: { duration: 0.1, lift: -2 },
  press: { duration: 0.1, scale: 0.96 },
  goldRule: { duration: 0.3, ease: ease.standard },
  overture: { duration: 1.4, ease: ease.emphasized },
  wordmarkSettle: { duration: 1.1, fromTracking: "0.22em", rise: 8 },
  crestReveal: { duration: 0.8, ease: ease.emphasized },
  parallax: {"default":0.03,"hero":0.05},
  reduced: { duration: 0.1, ease: ease.linear },
  sharedElement: { duration: 0.5, ease: ease.emphasized },
} as const;

/** Type: fixed + fluid scale and the landing's roles. */
export const type = {
  "scale": {
    "xs": "0.75rem",
    "sm": "0.875rem",
    "base": "1rem",
    "lg": "1.125rem",
    "xl": "1.25rem",
    "2xl": "clamp(1.25rem, 1.1522rem + 0.435vw, 1.5rem)",
    "3xl": "clamp(1.5rem, 1.3533rem + 0.652vw, 1.875rem)",
    "4xl": "clamp(1.75rem, 1.5543rem + 0.87vw, 2.25rem)",
    "5xl": "clamp(2.125rem, 1.7826rem + 1.522vw, 3rem)",
    "6xl": "clamp(2.5rem, 2.0109rem + 2.174vw, 3.75rem)",
    "7xl": "clamp(2.875rem, 2.2391rem + 2.826vw, 4.5rem)",
    "8xl": "clamp(3.5rem, 2.5217rem + 4.348vw, 6rem)",
    "9xl": "clamp(4rem, 2.4348rem + 6.957vw, 8rem)"
  },
  "lineHeight": {
    "xs": 1.5,
    "sm": 1.55,
    "base": 1.62,
    "lg": 1.55,
    "xl": 1.45,
    "2xl": 1.3,
    "3xl": 1.2,
    "4xl": 1.12,
    "5xl": 1.06,
    "6xl": 1.02,
    "7xl": 1,
    "8xl": 0.98,
    "9xl": 0.96
  },
  "letterSpacing": {
    "xs": "0.01em",
    "sm": "0.005em",
    "base": "0",
    "lg": "0",
    "xl": "0",
    "2xl": "0.005em",
    "3xl": "0.005em",
    "4xl": "0.005em",
    "5xl": "0.005em",
    "6xl": "0.006em",
    "7xl": "0.008em",
    "8xl": "0.01em",
    "9xl": "0.012em"
  },
  "roles": {
    "wordmark": {
      "fontSize": "clamp(4.5rem, 12vw, 12.5rem)",
      "lineHeight": 0.85,
      "letterSpacing": "0.15em",
      "fontWeight": 500
    },
    "display-xl": {
      "fontSize": "clamp(4rem, 2.4348rem + 6.957vw, 8rem)",
      "lineHeight": 0.96,
      "letterSpacing": "0.012em",
      "fontWeight": 500
    },
    "display-l": {
      "fontSize": "clamp(3.5rem, 2.5217rem + 4.348vw, 6rem)",
      "lineHeight": 0.98,
      "letterSpacing": "0.01em",
      "fontWeight": 500
    },
    "display-m": {
      "fontSize": "clamp(2.125rem, 1.7826rem + 1.522vw, 3rem)",
      "lineHeight": 1.06,
      "letterSpacing": "0.005em",
      "fontWeight": 500
    },
    "display-s": {
      "fontSize": "clamp(1.5rem, 1.3533rem + 0.652vw, 1.875rem)",
      "lineHeight": 1.2,
      "letterSpacing": "0.005em",
      "fontWeight": 500
    },
    "stat": {
      "fontSize": "clamp(3.5rem, 2.5217rem + 4.348vw, 6rem)",
      "lineHeight": 1,
      "letterSpacing": "0",
      "fontWeight": 400
    },
    "lede": {
      "fontSize": "clamp(1.25rem, 1.1522rem + 0.435vw, 1.5rem)",
      "lineHeight": 1.4,
      "letterSpacing": "0",
      "fontWeight": 400
    },
    "body-lg": {
      "fontSize": "1.125rem",
      "lineHeight": 1.62,
      "letterSpacing": "0",
      "fontWeight": 400
    },
    "body": {
      "fontSize": "1rem",
      "lineHeight": 1.62,
      "letterSpacing": "0",
      "fontWeight": 400
    },
    "caption": {
      "fontSize": "0.875rem",
      "lineHeight": 1.5,
      "letterSpacing": "0.005em",
      "fontWeight": 400
    },
    "overline": {
      "fontSize": "0.75rem",
      "lineHeight": 1.2,
      "letterSpacing": "0.32em",
      "fontWeight": 500
    },
    "label": {
      "fontSize": "0.75rem",
      "lineHeight": 1.2,
      "letterSpacing": "0.14em",
      "fontWeight": 600
    },
    "button": {
      "fontSize": "0.875rem",
      "lineHeight": 1,
      "letterSpacing": "0.06em",
      "fontWeight": 500
    }
  },
  "families": {
    "display": "var(--font-cormorant), 'Cormorant Garamond', Georgia, 'Times New Roman', serif",
    "text": "var(--font-text), \"Suisse Int'l\", -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    "mono": "var(--font-plex-mono), 'IBM Plex Mono', ui-monospace, 'SF Mono', Menlo, monospace"
  }
} as const;

/** Names of every font-size utility — consumed by lib/cn.ts (tailwind-merge). */
export const textSizes = ["xs","sm","base","lg","xl","2xl","3xl","4xl","5xl","6xl","7xl","8xl","9xl","wordmark","display-xl","display-l","display-m","display-s","stat","lede","body-lg","body","caption","overline","label","button"] as const;

export const layout = {
  "page": "1200px",
  "measure": "68ch",
  "margin": {
    "base": "1.25rem",
    "md": "1.5rem",
    "lg": "2rem",
    "xl": "2.5rem",
    "2xl": "3rem"
  },
  "gutter": {
    "base": "1rem",
    "md": "1.25rem",
    "lg": "1.5rem",
    "2xl": "2rem"
  },
  "sectionPad": "clamp(6rem, 12vh, 10rem)",
  "sectionPadSm": "4.5rem",
  "navHeight": "4rem",
  "navHeightMd": "5rem",
  "touchTarget": "44px"
} as const;

export const focusRing = {"width":"2px","offset":"3px"} as const;

export const breakpoints = {"sm":"640px","md":"768px","lg":"1024px","xl":"1280px","2xl":"1536px"} as const;
